<a href="https://colab.research.google.com/github/Fen-Pang/Capstone-Market-Analysis/blob/main/Market_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Part 1: Descriptive Analysis on Sales

## 1. Import libraries and data files

In [6]:
## Import customer and purchase datasets from GitHub into Google Colab
import pandas as pd
customer = pd.read_csv('https://raw.githubusercontent.com/Fen-Pang/Capstone-Market-Analysis/main/customer.csv')
purchase = pd.read_csv('https://raw.githubusercontent.com/Fen-Pang/Capstone-Market-Analysis/main/purchase.csv')
customer.head()

  customer_id     first_name last_name  gender  age country  income
0     CS00001        Isadora     Porto  Female   19  Brazil  117196
1     CS00002           Hugo   Carreño    Male   33   Chile   49256
2     CS00003           René   Olivera    Male   65  Mexico   33434
3     CS00004  Luiz Henrique     Pinto    Male   55  Brazil   75302
4     CS00005       Leonardo  Monteiro    Male   19  Brazil   32280

## 2. Exploratory Data Analysis (EDA)

In [9]:
# 2.1: Check dataset on number of rows and columns
print(customer.shape)
print(purchase.shape)

# Outcome: 1,001 customers and 50,000 purchases

(1001, 7)
(50000, 11)

In [16]:
# 2.2: Check dataset on column names, data types and missing values
customer.info()
purchase.info()

# Outcome: Order date and shipping date are stored as object.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  1001 non-null   object
 1   first_name   1001 non-null   object
 2   last_name    1001 non-null   object
 3   gender       1001 non-null   object
 4   age          1001 non-null   int64
 5   country      1001 non-null   object
 6   income       1001 non-null   int64
dtypes: int64(2), object(5)
memory usage: 54.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       50000 non-null  object
 1   customer_id    50000 non-null  object
 2   product_name   50000 non-null  object
 3   description    50000 non-null  object
 4   price          50000 non-null  float64
 5   discount       50000 non-null  float64
 6   tax            50000 non-null  float64
 7   order_date     50000 non-null  object
 8   quantity       50000 non-null  int64
 9   shipping_cost  50000 non-null  float64
 10  shipping_date  50000 non-null  object
dtypes: float64(4), int64(1), object(6)
memory usage: 4.2+ MB

In [14]:
# 2.3: Check dataset for missing values in both datasets
print(customer.isnull().sum())
print(purchase.isnull().sum())

# Outcome: No missing values

customer_id    0
first_name     0
last_name      0
gender         0
age            0
country        0
income         0
dtype: int64
order_id         0
customer_id      0
product_name     0
description      0
price            0
discount         0
tax              0
order_date       0
quantity         0
shipping_cost    0
shipping_date    0
dtype: int64

In [12]:
#2.4: Check dataset for duplicate rows in both datasets
print(customer.duplicated().sum())
print(purchase.duplicated().sum())

# Outcome: No duplicate

0
0

In [15]:
#2.5:  Check basic statistics of both datasets
display(customer.describe())
display(purchase.describe())

# Outcome: Average customer age is 41 and income is 84,629.
# Average purchase price is 1,275.93.

               age         income
count  1001.000000    1001.000000
mean     41.337662   84628.809191
std      13.732657   37498.010417
min      18.000000   20205.000000
25%      29.000000   52092.000000
50%      41.000000   83654.000000
75%      53.000000  116549.000000
max      65.000000  149980.000000

              price      discount           tax      quantity  shipping_cost
count  50000.000000  50000.000000  50000.000000  50000.000000   50000.000000
mean    1275.926873      0.249116      0.050081      5.497560      27.509281
std     1315.400328      0.144386      0.029159      2.862313      12.952128
min       20.020000      0.000000      0.000000      1.000000       5.000000
25%      219.675000      0.120000      0.030000      3.000000      16.360000
50%      834.395000      0.250000      0.050000      5.000000      27.580000
75%     1837.397500      0.370000      0.080000      8.000000      38.670000
max     4999.950000      0.500000      0.100000     10.000000      50.000000

## 3. Data Cleansing & Preparation